name: Continuous integration in a box
on: [push, pull_request]

jobs:
  Containerized-CI:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rte-kernels: [default, openacc]
        container: ["earthsystemradiation/rte-rrtmgp-ci:ifort","earthsystemradiation/rte-rrtmgp-ci:nvfortran"]
    container:
      image: ${{ matrix.container }}
    env:
      NCHOME: /home/runner/netcdf-c
      NFHOME: /home/runner/netcdf-fortran
      RFMIP_DIR: /home/runner/rfmip-files
    steps:
    ############################################################################
    # Checks out repository under $GITHUB_WORKSPACE
    - name: Check out code
      uses: actions/checkout@v2

    - name: Environmental variables
      run: |
        echo "RRTMGP_ROOT=${GITHUB_WORKSPACE}"    >> $GITHUB_ENV
        echo "PROF_DIR=${GITHUB_WORKSPACE}/tests" >> $GITHUB_ENV
    - name: Environmental variables - ifort
      if: contains(matrix.container, 'ifort')
      run: |
        echo "FCFLAGS=-m64 -g  -traceback -heap-arrays -assume realloc_lhs -extend-source 132 -check bounds,uninit,pointers,stack -stand f08 -prof-gen=srcpos" >> $GITHUB_ENV
    - name: Environmental variables - nvfortran
      if: contains(matrix.container, 'nvfortran')
      run:
        echo "FCFLAGS=-Mallocatable=03 -Mstandard -Mbounds -Mchkptr -Kieee -Mchkstk" >> $GITHUB_ENV

    - name: Make library, examples, tests
      shell: bash
      env:
        RTE_KERNELS: ${{ matrix.rte-kernels }}
      run: |
        source /opt/intel/oneapi/setvars.sh || true
        cd ${RRTMGP_ROOT}
        ${FC} --version
        make -C build -j 2
        make -C tests -j 1
        make -C examples/all-sky -j 2
        make -C examples/rfmip-clear-sky -j 2
    ############################################################################
    - name: Cache RFMIP files
      id: cache-rfmip-files
      uses: actions/cache@v2
      with:
        path: /home/runner/rfmip-files # Same as #{RFMIP_DIR}
        key: rfmip-files

    - name: Stage RFMIP files
      if: steps.cache-rfmip-files.outputs.cache-hit != 'true'
      run: |
        mkdir -p ${RFMIP_DIR}
        cd ${RFMIP_DIR}
        python3 ${RRTMGP_ROOT}/examples/rfmip-clear-sky/stage_files.py
    ############################################################################
    # Would be great to encode version info
    - name: Run examples, tests
      shell: bash
      env:
        LD_LIBRARY_PATH: /home/runner/netcdf-c/lib
      run: |
        source /opt/intel/oneapi/setvars.sh || true
        export LD_LIBRARY_PATH=${NFHOME}/lib:${LD_LIBRARY_PATH}
        cd ${RRTMGP_ROOT}/examples/rfmip-clear-sky
        cp ${RFMIP_DIR}/* .
        python3 ./run-rfmip-examples.py --block_size 8
        cd  ${RRTMGP_ROOT}/examples/all-sky
        python3 ./run-allsky-example.py
        cd  ${RRTMGP_ROOT}/tests
        cp ${RRTMGP_ROOT}/examples/rfmip-clear-sky/multiple_input4MIPs_radiation_RFMIP_UColorado-RFMIP-1-2_none.nc test_atmospheres.nc
        ./clear_sky_regression test_atmospheres.nc ${RRTMGP_ROOT}/rrtmgp/data/rrtmgp-data-lw-g256-2018-12-04.nc
        ./clear_sky_regression test_atmospheres.nc ${RRTMGP_ROOT}/rrtmgp/data/rrtmgp-data-sw-g224-2018-12-04.nc
    - name: Comparison
      run: |
        cd ${RRTMGP_ROOT}/examples/rfmip-clear-sky
        python3 ./compare-to-reference.py --fail=7.e-4
        cd ${RRTMGP_ROOT}/examples/all-sky
        python3 ./compare-to-reference.py
        cd ${RRTMGP_ROOT}/tests
        python3 verification.py
    ############################################################################
    - name: Generate code coverage XML
      shell: bash
      if: contains(matrix.container, 'ifort')
      run: |
        source /opt/intel/oneapi/setvars.sh || true
        cd ${PROF_DIR}
        profmerge -a
        echo "
        mo_
        ~mo_simple_netcdf
        ~mo_rfmip_io
        ~mo_testing_io
        ~mo_garand_atmos_io
        ~mo_load" > intel_codecov_filter.txt
        codecov -prj rte-rrtmgp -comp intel_codecov_filter.txt -xmlbcvrg ${{ matrix.rte-kernels }}_bcvrg.xml
    - name: Code coverage upload
    - uses: codecov/codecov-action@v1
      if: contains(matrix.container, 'ifort')
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ${{ matrix.rte-kernels }}_bcvrg.xml
        # flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: false # optional (default = false)
        verbose: true # optional (default = false)
    - name: Validation plots
      if: contains(matrix.rte-kernels, 'default')
      run: |
        cd ${RRTMGP_ROOT}/tests
        python3 validation-plots.py
    - name: Upload plots
      if: contains(matrix.container, 'ifort') && contains(matrix.rte-kernels, 'default')
      uses: actions/upload-artifact@v2
      with:
        name: validation-and-code-coverage
        path: tests/validation-figures.pdf
